language: c

before_script: sudo apt-get install -y check

script:
    - ./autogen.sh
    - make
    - make check
    - cat tests/test-suite.log || true

notifications:
  email:
    - lars@strojny.net
