language: c

os:
    - linux
    - osx

before_script: sudo apt-get install -y check || brew install check

script:
    - ./autogen.sh
    - make
    - make check
    - cat tests/test-suite.log || true

notifications:
  email:
    - lars@strojny.net
